export const keyCodes = {
  'backspace': 'Backspace',
  'tab': 'Tab',
  'enter': 'Enter',
  'shift': 'Shift',
  'ctrl': 'Control',
  'alt': 'Alt',
  'pause': 'Pause',
  'caps lock': 'CapsLock',
  'escape': 'Escape',
  'space': 'Space',
  'page up': 'PageUp',
  'page down': 'PageDown',
  'end': 'End',
  'home': 'Home',
  'ArrowLeft': 'ArrowLeft',
  'ArrowUp': 'ArrowUp',
  'ArrowRight': 'ArrowRight',
  'ArrowDown': 'ArrowDown',
  'print screen': 'PrintScreen',
  'insert': 'Insert',
  'delete': 'Delete',
  '0': 'Digit0',
  '1': 'Digit1',
  '2': 'Digit2',
  '3': 'Digit3',
  '4': 'Digit4',
  '5': 'Digit5',
  '6': 'Digit6',
  '7': 'Digit7',
  '8': 'Digit8',
  '9': 'Digit9',
  'a': 'KeyA',
  'b': 'KeyB',
  'c': 'KeyC',
  'd': 'KeyD',
  'e': 'KeyE',
  'f': 'KeyF',
  'g': 'KeyG',
  'h': 'KeyH',
  'i': 'KeyI',
  'j': 'KeyJ',
  'k': 'KeyK',
  'l': 'KeyL',
  'm': 'KeyM',
  'n': 'KeyN',
  'o': 'KeyO',
  'p': 'KeyP',
  'q': 'KeyQ',
  'r': 'KeyR',
  's': 'KeyS',
  't': 'KeyT',
  'u': 'KeyU',
  'v': 'KeyV',
  'w': 'KeyW',
  'x': 'KeyX',
  'y': 'KeyY',
  'z': 'KeyZ',
  'left window key': 'MetaLeft',
  'right window key': 'MetaRight',
  'select key': 'ContextMenu',
  'numpad 0': 'Numpad0',
  'numpad 1': 'Numpad1',
  'numpad 2': 'Numpad2',
  'numpad 3': 'Numpad3',
  'numpad 4': 'Numpad4',
  'numpad 5': 'Numpad5',
  'numpad 6': 'Numpad6',
  'numpad 7': 'Numpad7',
  'numpad 8': 'Numpad8',
  'numpad 9': 'Numpad9',
  'multiply': 'NumpadMultiply',
  'add': 'NumpadAdd',
  'subtract': 'NumpadSubtract',
  'decimal point': 'NumpadDecimal',
  'divide': 'NumpadDivide',
  'f1': 'F1',
  'f2': 'F2',
  'f3': 'F3',
  'f4': 'F4',
  'f5': 'F5',
  'f6': 'F6',
  'f7': 'F7',
  'f8': 'F8',
  'f9': 'F9',
  'f10': 'F10',
  'f11': 'F11',
  'f12': 'F12',
  'num lock': 'NumLock',
  'scroll lock': 'ScrollLock',
  'bracketLeft': 'BracketLeft',
  'bracketRight': 'BracketRight',
  'semicolon': 'Semicolon',
  'quote': 'Quote',
  'comma': 'Comma',
  'period': 'Period',
  'slash': 'Slash',
  'backslash': 'Backslash',
  'backquote': 'Backquote',
  'minus': 'Minus',
  'equal': 'Equal',
};

Object.freeze(keyCodes);
